### ISSUE TITLE
logger configuration overrides project's logger

### ISSUE THREAD

**Issue by helmanofer** [ariddell/lda#24]
in my main code I configure:

    logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

But I get lda's logger configuration:

    INFO:lda:<450> log likelihood: -111, per-word: -3.4701
    INFO:lda:<460> log likelihood: -111, per-word: -3.4701
    INFO:lda:<470> log likelihood: -111, per-word: -3.4701
    INFO:lda:<480> log likelihood: -111, per-word: -3.4701

If in lda's init file I mark out line 11:
    
    ...
    __version__ = pbr.version.VersionInfo('lda').version_string()

    # logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger('lda')
    logger.addHandler(logging.NullHandler())

I get the correct logger config:
   
    2015-02-23 16:05:37,286 : INFO : <470> log likelihood: -111, per-word: -3.4701
    2015-02-23 16:05:37,288 : INFO : <480> log likelihood: -111, per-word: -3.4701
    2015-02-23 16:05:37,290 : INFO : <490> log likelihood: -111, per-word: -3.4701
    2015-02-23 16:05:37,291 : INFO : <500> log likelihood: -111, per-word: -3.4701

I took this from gensim's init file.

**Comment by ariddell** [comment]
Thanks. I've seen this problem in a few projects and would like to figure out what's the right way to setup logging properly. I'll look at the logging docs today.

**Comment by ariddell** [comment]
Removing that line disables all logging, which isn't what we want.

Maybe the appropriate place to put basicConfig is in the `__init__` for LDA.
