### ISSUE TITLE
"ImportError: No module named _lda" on linux

### ISSUE THREAD

**Issue by matthiasmauch** [ariddell/lda#25]
Hi,

I apologise in advance if this is not an issue with the software but our own server.

I installed and used lda on my local Mac (with anaconda) without problems, both with pip install and the install from source via make + python setup.py install. However, neither appears to work on our linux server (with anaconda). The lda library appears to be installed, i.e.

    In [1]: import l
    lda            libfuturize    linecache      llpython       llvm_array     llvmpy         logging        
    lib2to3        libpasteurize  linuxaudiodev  llvm           llvm_cbuilder  locale         lxml  

but when I actually load it, I get

    In [1]: import lda
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-4b4ad2b47765> in <module>()
    ----> 1 import lda
    
    /homes/matthiasm/code/lda/lda/__init__.py in <module>()
          5 import pbr.version
          6 
    ----> 7 from lda.lda import LDA  # noqa
          8 
          9 __version__ = pbr.version.VersionInfo('lda').version_string()
    
    /homes/matthiasm/code/lda/lda/lda.py in <module>()
          8 import numpy as np
          9 
    ---> 10 import lda._lda
         11 import lda.utils
         12 
    
    ImportError: No module named _lda

Any hints to how I might resolve this?

Cheers,
Matthias

**Comment by ariddell** [comment]
Are you running this from the directory you installed it from?

**Comment by matthiasmauch** [comment]
Hm, I did. And it turns out it wasn't actually installed. Now I gotta understand why it didn't install.

**Comment by matthiasmauch** [comment]
Btw, thanks for being so responsive!

**Comment by ariddell** [comment]
Whatever you do -- don't try "import lda" from the source directory. Python gets confused. See the Linux install instructions in the docs -- let me know if I should make any changes. I'm not entirely opposed to adding an Anaconda note if there needs to be one.

**Comment by matthiasmauch** [comment]
On 11 Mar 2015, at 16:37, Allen Riddell <notifications@github.com> wrote:

> Whatever you do -- don't try "import lda" from the source directory. Python gets confused. See the Linux install instructions in the docs -- let me know if I should make any changes. I'm not entirely opposed to adding an Anaconda note if there needs to be one.

Yeah, seems like it was due to me running stuff in the source directory.
I can run it fine now.

I don�t think there�s no need to add an Anaconda note. Thanks!

Cheers,
Matthias

**Comment by ariddell** [comment]
Great. Glad it works.
