### ISSUE TITLE
LDA without a known number of clusters

### ISSUE THREAD

**Issue by longhotsummer** [ariddell/lda#29]
Do you have any advice for using LDA when the number of clusters is unknown a priori?

**Comment by ariddell** [comment]
In any event, it's best not to take the number of topics literally. To some extent it is like picking a number of components for Principle Components Analysis (i.e., it's arbitrary and has a lot to do with the vagaries of the model). For lda I'd typically pick 100 topics and leave it at that (unless it's a really massive and heterogeneous corpus). If you use MALLET and hca you can let the models pick a number of topics for you in a certain sense: pick a very high number of topics (500-1000) and then filter out the topics which are insignificant. (Soon you'll be able to do this with `lda`.)

**Comment by xashely** [comment]
what about select the outperform topics or words,that is deal with the sparsity of topics and words.i wish it has some useful for you.
