### ISSUE TITLE
Installation fails (using pip and cloning the repo)

### ISSUE THREAD

**Issue by alangrafu** [ariddell/lda#36]
After running `pip install lda` I go to the python interpreter and I got

```python
>>> import lda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lda/__init__.py", line 7, in <module>
    from lda.lda import LDA  # noqa
  File "lda/lda.py", line 10, in <module>
    import lda._lda
ImportError: No module named _lda
```

Alternatively, I cloned the repo and ran `python setup.py build` and i got

```
error: can't copy 'lda/_lda.c': doesn't exist or not a regular file
```

**Comment by ariddell** [comment]
Thanks for the report!

If you're on linux, there are some linux-specific install instructions in the documentation. If you're not on linux, let me know what OS you're using and I can figure out what's wrong.

**Comment by alangrafu** [comment]
I'm using OS X Yosemite

**Comment by ariddell** [comment]
Very strange. It should download the precompiled binary for OS X. Can you tell me what version of ``pip`` you have installed? (``pip --version``)

**Comment by alangrafu** [comment]
pip 1.5.4 with python 2.7

As I said before, I also found `error: can't copy 'lda/_lda.c': doesn't exist or not a regular file` when trying to compile from the source. Maybe it is related?

**Comment by ariddell** [comment]
Did ``pip install lda`` run successfully the first time? (if you are in a directory where you have the lda source, try changing out of that directory and trying ``import lda`` again.)

**Comment by alangrafu** [comment]
Yes, I got

```
pip install lda
Downloading/unpacking lda
  Downloading lda-1.0.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (377kB): 377kB downloaded
Downloading/unpacking numpy>=1.6.1,<2.0 (from lda)
  Downloading numpy-1.9.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB): 3.7MB downloaded
Downloading/unpacking pbr>=0.6,!=0.7,<1.0 (from lda)
  Downloading pbr-0.11.0-py2.py3-none-any.whl (78kB): 78kB downloaded
Requirement already satisfied (use --upgrade to upgrade): pip in ./_env/lib/python2.7/site-packages (from pbr>=0.6,!=0.7,<1.0->lda)
Installing collected packages: lda, numpy, pbr
Successfully installed lda numpy pbr
Cleaning up...
```

**Comment by alangrafu** [comment]
Immediately after that I run into this

```python
python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lda.py", line 3, in <module>
    X = lda.datasets.load_reuters()
AttributeError: 'module' object has no attribute 'datasets'
>>>
```

**Comment by ariddell** [comment]
Do you have something called lda.py in the current directly? Line 3 of lda.py (in the source code) is not the line above.

**Comment by alangrafu** [comment]
Crap! it had a lda folder. I moved it and it worked fine. Sorry for the confusion, thanks!
