### ISSUE TITLE
assign or increase higher probability for a doc belonging to a topic?

### ISSUE THREAD

**Issue by fairsky66** [ariddell/lda#46]
Is there any way or principle to achieve this goal?

Take an example for simplicity, docA have two prob.dists, such as P(topic=1)=0.21, P(topic=2)=0.22.
How to produce a higher P for docA in topic1 or topic2 or assign one?

**Comment by ariddell** [comment]
Thanks for the comment. You can do this sort of thing with MALLET or hca without too much difficulty. It also wouldn't be too hard to modify the code to accept more detailed hyperparameters.

Right now I'm focusing on making everything work beautifully out of the box without any/much parameter fiddling. For example, I'm probably going to do hyperparameter sampling soon.
