### ISSUE TITLE
iterated pseudo-counts in transform_single

### ISSUE THREAD

**Issue by ecolss** [ariddell/lda#49]
The algorithm of inferencing the topics on new unseen docs is mentioned in `transform` method, i.e. iterated pseudo-counts (I missed this NOTE at first).

AFAIK, however the inference on new doc is typically implemented using gibbs sampling too, could you please give me some brief hints on how these two methods differ from each other in terms of accuracy and efficiency?

**Comment by ariddell** [comment]
The Buntine paper answers all these questions.

Buntine, Wray. “Estimating Likelihoods for Topic Models.” In Advances in Machine Learning, First Asian Conference on Machine Learning, 51–64, 2009. doi:http://dx.doi.org/10.1007/978-3-642-05224-8_6.

The full citation is missing. This is a bug!

**Comment by ariddell** [comment]
Closed in 4ad593097e2a2f07a6946a1600eb3dd1522109d4
