### ISSUE TITLE
How to run from modified source?

### ISSUE THREAD

**Issue by kerryz** [ariddell/lda#51]
Thanks for an excellent LDA implementation in Cython.

I'm developing a model that extends the LDA-model and thus I need to modify the source code in this package and then run it straight from my locally modified source code. However, when trying to import the package `lda` from the source directory, I run into the same problem as #25 "ImportError: No module named _lda" (I'm also using Ubuntu 14.04).

What would the best approach be to run a locally modified version of this package?

**Comment by ariddell** [comment]
If you're willing to work in the source directory you could try

```
make cython
python setup.py build_ext --inplace
```

The import problem should go away.

**Comment by kerryz** [comment]
Yes, this solves the issue, thank you!

**Comment by kerryz** [comment]
I can build this inplace on one of my computers, on the other one, however, I get

```
$ python setup.py build_ext --inplace
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pbr/core.py", line 109, in pbr
    attrs = util.cfg_to_args(path)
  File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 243, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/local/lib/python2.7/dist-packages/pbr/hooks/__init__.py", line 26, in setup_hook
    backwards.BackwardsCompatConfig(config).run()
  File "/usr/local/lib/python2.7/dist-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/local/lib/python2.7/dist-packages/pbr/hooks/backwards.py", line 33, in hook
    strip_markers=True))
  File "/usr/local/lib/python2.7/dist-packages/pbr/packaging.py", line 99, in parse_requirements
    for line in get_reqs_from_files(requirements_files):
  File "/usr/local/lib/python2.7/dist-packages/pbr/packaging.py", line 81, in get_reqs_from_files
    return fil.read().split('\n')
IOError: [Errno 5] Input/output error
error in setup command: Error parsing /home/kerryz/Documents/Skolarbeten/Kex/code/python_lda/setup.cfg: IOError: [Errno 5] Input/output error
```

The computer that successfully builds it has `pbr` version 0.10.7, but downgrading `pbr` didn't solve the issue either. Any ideas @ariddell or is it `pbr`'s problem?

**Comment by ariddell** [comment]
Any idea what "Errno 5" means?

**Comment by kerryz** [comment]
According to the [Python docs](https://docs.python.org/2/library/errno.html) the error integer value is borrowed from linux errno. 5 is simply I/O error

    $ errno 5
    EIO 5 Input/output error

which isn't very specific...

**Comment by ariddell** [comment]
Closing this issue for now.
