### ISSUE TITLE
Is it a bug？

### ISSUE THREAD

**Issue by HHself** [ariddell/lda#54]
Maybe I say a error in file lda.py line 261：
     N = int(X.sum())
     N means the number of words, but here is the sum of all index. Maybe it is:  sum the len of each element in X , sum([len(i) for i in X])?

**Comment by ariddell** [comment]
X.sum() should get the sum of entries in the document-term matrix (for sparse and dense arrays). This is equal to the number of words. Do you have an example where this doesn't produce the right result?
