### ISSUE TITLE
Is it possible to get topic assignments of words?

### ISSUE THREAD

**Issue by JasonThu** [ariddell/lda#55]
Thanks for your great work! 

I checked the documentation, it seems that I could only get counts of topic-word assignments(nzw_). 

So is it possible to get topic assignments of words?

**Comment by ariddell** [comment]
Do you mean ``model.topic_word_``?

**Comment by JasonThu** [comment]
Thanks for the reply!
But what I want to know is the specific topic assigned to each word, rather than topic-word distribution.

**Comment by ariddell** [comment]
lda doesn't keep track of word order so there's no explicit tracking of
topic assignment to specific words.

You can, however, sample the topic assignment for an individual word
given knowledge of the posterior distribution.

**Comment by JasonThu** [comment]
Got it.

Thanks very much :)
