### ISSUE TITLE
Pip not installing if dependencies are not already satisfied

### ISSUE THREAD

**Issue by CyrilBos** [ariddell/lda#64]
Hi, 
I did not have pbr installed and running pip3 install lda froze after collecting the zip file (Python 3.6). I cancelled it and installed pbr and it worked.

**Comment by ariddell** [comment]
Releasing wheels should solve this. Thanks for the reminder. Relevant issue is #59.

**Comment by ariddell** [comment]
You're good to go. ``pip install lda`` should work now on Python 3.6.
